### ISSUE TITLE
Allow Optional files for Jobs

### ISSUE THREAD

**Issue by reyery** [cooling-singapore/saas-middleware#101]
**Description**
Currently the RTI is really strict on what a processor should produce after a job has completed. The RTI expects every file as described in the `output` property of the processor descriptor. However there could instances where not all files would be created by a processor after a job, causing the RTI to fail the job. Allowing files to be marked optional in the descriptor would help this and allow for flexibility in processors.

However, on the other hand, this could actually be considered as a feature of the RTI as this ensures that processors fulfill their "promises"/"contract" as stated in the descriptor, avoid potential complications down the line (e.g. a post processor expects an input file that was supposedly created by the previous processor but could not find it).

**Outcomes**
- [ ] Decide whether this is important

**Comment by HeikoAydt** [comment]
Obsolete.
