### ISSUE TITLE
Differentiate between object ID and content ID provenance

### ISSUE THREAD

**Issue by reyery** [cooling-singapore/saas-middleware#221]
**Description**
Due to how a single content ID (based on the hash of the data object) could have multiple object IDs (based on the hash of the meta data of the data object) related to it, the provenance of a single data object could have multiple provenance history (based on content ID). 

Instead of showing all the different histories based on the content ID, we should only show provenance based on the object ID that fits better to the context of the object.

**Outcomes**
- [ ] Decide on a plan of attack to deal with the difference

**Comment by HeikoAydt** [comment]
Obsolete.
