### ISSUE TITLE
Issues with running saas-mw on Windows

### ISSUE THREAD

**Issue by reyery** [cooling-singapore/saas-middleware#240]
**Bug Description**
While trying to run the saas-middleware service on Windows or use SSH to deploy processors to a remote Windows machine, I have encountered a few issues:

- `KeyError` when trying to access environment variable `HOME` during deployment. It does not exist by default in Windows, but could be added manually.
- Windows permission error when trying to add gpp using cli. When the saas-middleware clones the remote repo to analyse it then tries to delete it after, there will be a permission error trying to delete the repo folder, maybe due to it being marked as read-only.
- F-strings have problems with Windows path. Since Windows uses backslash for paths, it could be thought as escape characters in python string. The result is that the path would become `UsersUserDirectory` instead of `C:\Users\User\Directory`

- Enclose SSH password in quotes, due to some special characters in the password escaping the command. e.g. `(`
- Problems with git credentials for windows when using git remotely using SSH.
    - https://github.com/GitCredentialManager/git-credential-manager/blob/main/docs/credstores.md#windows-credential-manager=
    - could be solved by adding to .gitconfig
```
[credential]
    helper =

```
- Git in windows does not expand `~` to user home directory, results in folder being created in a folder name `~` instead.

**Comment by HeikoAydt** [comment]
@reyery what is the status on this one?

**Comment by reyery** [comment]
@HeikoAydt I think most of the issues here should already be fixed. But there is one that is we are actually currently facing, we can track that in the other issue we have.

> - F-strings have problems with Windows path. Since Windows uses backslash for paths, it could be thought as escape characters in python string. The result is that the path would become UsersUserDirectory instead of C:\Users\User\Directory
