### ISSUE TITLE
Migrate NodeDB from SQLite to MongoDB

### ISSUE THREAD

**Issue by reyery** [cooling-singapore/saas-middleware#295]
**Description**
Migrate NodeDB from SQLite to MongoDB

**Comment by HeikoAydt** [comment]
@reyery what was again the rationale behind migrating to MongoDB?

**Comment by reyery** [comment]
@HeikoAydt I think it was because a lot of the values that we were storing were JSON objects, so storing them in MongoDB would make more sense instead of storing it as a string.
