### ISSUE TITLE
Allow DOR to support using AWS S3 as a backend

### ISSUE THREAD

**Issue by reyery** [cooling-singapore/saas-middleware#399]
**Description**
As part of our move to move to AWS, we can also allow the DOR to make use of AWS S3 for scalable file storage. This would help prevent the issue of insufficient disk space that we sometimes encounter. It might still be useful to keep the local disk implementation to allow flexibility of deployment/testing.

A flag or environment variable can be used to indicate which backend the DOR should use during startup.

**Comment by reyery** [comment]
This could apply also apply to databases (user accounts for explorer apps) and job queues (message queue)

**Comment by HeikoAydt** [comment]
Obsolete.
